// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function twoFer(name) {
  var name$1 = name !== undefined ? name : "you";
  return "One for " + (name$1 + ", one for me.");
}

exports.twoFer = twoFer;
/* No side effect */
