// Generated by CoffeeScript 2.7.0
(function() {
  var DS;

  DS = require('./difference-of-squares');

  describe('Difference of Squares', function() {
    describe('Square the sum of the numbers up to the given number', function() {
      it('square of sum 1', function() {
        var result;
        result = DS.squareOfSum(1);
        return expect(result).toEqual(1);
      });
      it('square of sum 5', function() {
        var result;
        result = DS.squareOfSum(5);
        return expect(result).toEqual(225);
      });
      return it('square of sum 100', function() {
        var result;
        result = DS.squareOfSum(100);
        return expect(result).toEqual(25502500);
      });
    });
    describe('Sum the squares of the numbers up to the given number', function() {
      it('sum of squares 1', function() {
        var result;
        result = DS.sumOfSquares(1);
        return expect(result).toEqual(1);
      });
      it('sum of squares 5', function() {
        var result;
        result = DS.sumOfSquares(5);
        return expect(result).toEqual(55);
      });
      return it('sum of squares 100', function() {
        var result;
        result = DS.sumOfSquares(100);
        return expect(result).toEqual(338350);
      });
    });
    return describe('Subtract sum of squares from square of sums', function() {
      it('difference of squares 1', function() {
        var result;
        result = DS.differenceOfSquares(1);
        return expect(result).toEqual(0);
      });
      it('difference of squares 5', function() {
        var result;
        result = DS.differenceOfSquares(5);
        return expect(result).toEqual(170);
      });
      return it('difference of squares 100', function() {
        var result;
        result = DS.differenceOfSquares(100);
        return expect(result).toEqual(25164150);
      });
    });
  });

}).call(this);

//# sourceMappingURL=difference-of-squares.spec.js.map
