name = "resistor-color-trio"
version = "0.1.0"
defaultTargets = ["ResistorColorTrioTest"]
testDriver = "ResistorColorTrioTest"
moreLeanArgs = [ "-DwarningAsError=true" ]

[[lean_lib]]
name = "LeanTest"
srcDir = "vendor/LeanTest"

[[lean_lib]]
name = "ResistorColorTrio"

[[lean_lib]]
name = "Extra"

[[lean_exe]]
name = "ResistorColorTrioTest"
root = "ResistorColorTrioTest"
