# Calculate the square of the sums of the first N natural numbers
# SquareOfSum ? Number
SquareOfSum ← |1 ⊙(⍤ "Please implement SquareOfSum" 0)

# Calculate the sum of the squares of the first N natural numbers
# SumOfSquares ? Number
SumOfSquares ← |1 ⊙(⍤ "Please implement SumOfSquares" 0)

# Calculate the difference between the square of sums and sum of squares
# DifferenceOfSquares ? Number
DifferenceOfSquares ← |1 ⊙(⍤ "Please implement DifferenceOfSquares" 0)
