// Generated by CoffeeScript 2.7.0
(function() {
  var Lineup;

  Lineup = class Lineup {
    static format(name, number) {
      var suffix;
      suffix = this.getSuffix(number);
      return `${name}, you are the ${number}${suffix} customer we serve today. Thank you!`;
    }

    static getSuffix(number) {
      var mod10, mod100;
      mod100 = number % 100;
      mod10 = number % 10;
      if (mod100 === 11 || mod100 === 12 || mod100 === 13) {
        return 'th';
      } else if (mod10 === 1) {
        return 'st';
      } else if (mod10 === 2) {
        return 'nd';
      } else if (mod10 === 3) {
        return 'rd';
      } else {
        return 'th';
      }
    }

  };

}).call(this);

//# sourceMappingURL=line-up.js.map
